### ISSUE TITLE
Android 5.x 

### ISSUE THREAD

**Issue by Xinul-Hacker** [farhansadik/EchoMinal#70]
Is there some place that I can find an offline bootstrap and/or download torrent for an Android 5.x termux.

I really want to use this on my older tablet offline.

Any direction would be greatly appreciated.

**Comment by farhansadik** [comment]
Hello @Xinul-Hacker 
Sorry, there is no way to work with termux in android 5x and 6x. Ref ~ https://github.com/farhansadik/echominal/issues/56

**Temporary Solution**
You can try this `legacy termux support` script, this may work some of packages. But most of the packages won't work. Even my `echominal` project won't work with this `legacy termux support` script. Best of luck.

**Manual Implementation** 
```bash
function mirror() {
	echo "deb https://termux.mentality.rip/termux-main/ stable main" > $PREFIX/etc/apt/sources.list
	echo "deb https://packages.termux.org/apt/termux-games games stable" > $PREFIX/etc/apt/sources.list.d/game.list
	echo "deb https://packages.termux.org/apt/termux-science science stable" > $PREFIX/etc/apt/sources.list.d/science.list
	pkg update && pkg upgrade;
}
```
Script ~ https://github.com/farhansadik/echominal-development/blob/master/legacy_termux.bash

Thank You, 
Farhan Sadik
